spring:
  application:
    name: compute-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8011
  
profile: hello-spring-cloud

#忽略权限拦截
management:
  security:
    enabled: false
    
feign:
  hystrix:
    enabled: true
    
#设置负载均衡策略
#此设置未生效，原因待查
compute-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
   
# 配置微服务跟踪sleuth
logging:
  level:
    root: INFO
    #org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
  
