spring:
  application:
    name: compute-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  zipkin:
#  base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8013
  
profile: hello-spring-cloud

#忽略权限拦截
management:
  security:
    enabled: false
  
